[project]
name = "rl-algos-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roshan R", email = "roshan.tsx@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "gym>=0.26.2",
    "highway-env>=1.12.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "ruff>=0.16.9",
    "torch>=2.14.1",
    "wandb>=0.30.0",
]

[project.scripts]
dev = "rl_algos_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
